Repository jazman43/Weather-App, pull requests merged in 2023-11, with the labels that each got.

#6 Rain radar with backend working
  weather_app_cs203_a2/api/migrations/0001_initial.py
  weather_app_cs203_a2/api/models.py
  weather_app_cs203_a2/api/serializers.py
  weather_app_cs203_a2/api/urls.py
  weather_app_cs203_a2/api/views.py
  weather_app_cs203_a2/frontend/package-lock.json
  weather_app_cs203_a2/frontend/package.json
  weather_app_cs203_a2/frontend/src/components/MainWeatherInfo.css
  weather_app_cs203_a2/frontend/src/components/MainWeatherWindow.js
  weather_app_cs203_a2/frontend/src/components/RainRadarWind.js
  weather_app_cs203_a2/frontend/static/css/index.css
  weather_app_cs203_a2/frontend/static/frontend/main.js
  weather_app_cs203_a2/frontend/static/frontend/main.js.LICENSE.txt
  weather_app_cs203_a2/weather_app_cs203_a2/settings.py
  weather_app_cs203_a2/weather_app_cs203_a2/urls.py
Labels: enhancement, help wanted

#7 Rain-Radar_maps-lining-up
  weather_app_cs203_a2/api/views.py
  weather_app_cs203_a2/frontend/src/components/App.js
  weather_app_cs203_a2/frontend/src/components/MainWeatherInfo.js
  weather_app_cs203_a2/frontend/src/components/MainWeatherWindow.js
  weather_app_cs203_a2/frontend/src/components/RainRadarWind.js
  weather_app_cs203_a2/frontend/static/css/index.css
  weather_app_cs203_a2/frontend/static/frontend/main.js
  weather_app_cs203_a2/package-lock.json
  weather_app_cs203_a2/package.json
Labels: enhancement

#10 Weather warnings - finished
  weather_app_cs203_a2/api/models.py
  weather_app_cs203_a2/api/serializers.py
  weather_app_cs203_a2/api/urls.py
  weather_app_cs203_a2/api/views.py
  weather_app_cs203_a2/frontend/src/components/MainWeatherWindow.js
  weather_app_cs203_a2/frontend/src/components/RainRadarWind.js
  weather_app_cs203_a2/frontend/src/components/WeaterWaringsWind.js
  weather_app_cs203_a2/frontend/static/frontend/main.js
Labels: enhancement

#11 css-to-main
  weather_app_cs203_a2/api/serializers.py
  weather_app_cs203_a2/api/views.py
  weather_app_cs203_a2/frontend/src/components/MainWeatherWindow.js
  weather_app_cs203_a2/frontend/src/components/RainRadarWind.js
  weather_app_cs203_a2/frontend/static/css/index.css
  weather_app_cs203_a2/frontend/static/frontend/main.js
Labels: enhancement

#12 Created offline functionality.
  weather_app_cs203_a2/frontend/src/components/MainWeatherWindow.js
  weather_app_cs203_a2/frontend/static/frontend/main.js
Labels: enhancement

#13 comments-added
  README.md
  weather_app_cs203_a2/api/serializers.py
  weather_app_cs203_a2/api/urls.py
  weather_app_cs203_a2/api/views.py
  weather_app_cs203_a2/frontend/src/components/App.js
  weather_app_cs203_a2/frontend/src/components/MainWeatherWindow.js
  weather_app_cs203_a2/frontend/src/components/RainRadarWind.js
  weather_app_cs203_a2/frontend/src/components/WeaterWaringsWind.js
  weather_app_cs203_a2/frontend/src/index.js
Labels: documentation, enhancement
